import { Link } from 'react-router-dom';
import { useCart } from '../context/CartContext';

export function CartPage() {
  const { cart, isLoading, isUpdating, errorMessage, updateQuantity, removeItem, refresh } = useCart();
  if (isLoading) return <main role="status" className="mx-auto max-w-5xl px-5 py-20 text-center text-[#5067aa]">Loading your bag…</main>;

  return <main className="mx-auto max-w-5xl px-5 py-12 sm:px-8 sm:py-16">
    <p className="text-xs font-semibold uppercase tracking-[0.2em] text-[#5067aa]">Your form&field edit</p><h1 className="mt-3 font-serif text-5xl">Your bag <span className="text-2xl text-[#5067aa]">({cart.itemCount})</span></h1>
    {errorMessage && <p role="alert" className="mt-6 rounded bg-red-50 p-4 text-sm text-red-800">{errorMessage} <button onClick={() => void refresh().catch(() => undefined)} className="ml-2 underline">Try again</button></p>}
    {!cart.items.length ? <div className="py-16 text-center"><p className="font-serif text-2xl">Your bag is taking a breather.</p><p className="mt-2 text-sm text-[#5067aa]">Find something lovely for your everyday.</p><Link to="/products" className="mt-6 inline-block rounded-full bg-[#32457b] px-7 py-3 text-sm text-white">Explore the collection</Link></div> : <div className="mt-10 grid gap-12 md:grid-cols-[1fr_300px]">
      <div className="divide-y divide-[#32457b]/10">{cart.items.map((item) => <article key={item.id} className="flex gap-5 py-6 first:pt-0"><div className="h-28 w-24 shrink-0 bg-[#86a6de]/20">{item.image_url && <img src={item.image_url} alt="" className="h-full w-full object-cover" />}</div><div className="flex flex-1 flex-col justify-between gap-4 sm:flex-row"><div><h2 className="font-serif text-xl">{item.product_name}</h2><p className="mt-1 text-sm text-[#5067aa]">{item.variant_name}</p><p className="mt-2 text-sm">${Number(item.price).toFixed(2)}</p>{!item.quantity_available && <p className="mt-2 text-xs text-red-700">Only a limited quantity remains.</p>}</div><div className="flex items-center gap-4"><label className="sr-only" htmlFor={`quantity-${item.id}`}>Quantity for {item.product_name}</label><select disabled={isUpdating || item.id.startsWith('pending-')} id={`quantity-${item.id}`} value={item.quantity} onChange={(event) => void updateQuantity(item.id, Number(event.target.value)).catch(() => undefined)} className="rounded border border-[#32457b]/20 bg-white px-3 py-2 text-sm">{Array.from({ length: Math.min(10, Math.max(item.quantity, item.quantity_available ? 10 : item.quantity)) }, (_, index) => index + 1).map((quantity) => <option key={quantity} value={quantity}>{quantity}</option>)}</select><button disabled={isUpdating} onClick={() => void removeItem(item.id).catch(() => undefined)} className="text-sm text-[#5067aa] underline underline-offset-4">Remove</button></div></div></article>)}</div>
      <aside className="h-fit bg-white p-6"><h2 className="font-serif text-2xl">Order summary</h2><div className="mt-5 flex justify-between text-sm"><span>Subtotal</span><span>${Number(cart.subtotal).toFixed(2)}</span></div><p className="mt-2 text-xs leading-5 text-[#5067aa]">Shipping and taxes are calculated at checkout.</p><div className="mt-5 flex justify-between border-t border-[#32457b]/10 pt-4 font-medium"><span>Total</span><span>${Number(cart.total).toFixed(2)}</span></div><Link to="/checkout" className="mt-6 block rounded-full bg-[#32457b] px-5 py-3.5 text-center text-sm font-medium text-white hover:bg-[#5067aa]">Continue to checkout</Link><Link to="/products" className="mt-4 block text-center text-sm underline underline-offset-4">Continue shopping</Link></aside>
    </div>}
  </main>;
}
